titan-misuzhima/compro/urls.py
from django.urls import path
from .views import beranda, profil_petinggi, kebijakan_mutu, karir

app_name='compro'
urlpatterns = [
    path('', beranda, name="beranda"),
    path('profil/', profil_petinggi, name="profil"),
    path('kebijakan-mutu/', kebijakan_mutu, name="kebijakan-mutu"),
    path('karir/', karir, name="karir")
]

titan-misuzhima/titan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from ui.views import mobile_homepage, login, auth_login, auth_logout, edit_user, change_pass, upload_profile_pict, webmail_redirect
from compro import urls as compro


admin.autodiscover()

urlpatterns = [
    path('admin/debug/', admin.site.urls),
    path('admin/', include('ui.urls')),
    url(r'^$', RedirectView.as_view(
        url='admin/dashboard/payroll', permanent=True), name='$'),
    path('pegawai/', mobile_homepage, name='mobile'),
    path('accounts/login/', login, name='login'),
    path('auth/login/', auth_login, name='auth_login'),
    path('auth/logout/', auth_logout, name='auth_logout'),
    path('edit/<nopeg>/', edit_user, name='edit_user'),
    path('update/picture/', upload_profile_pict, name='upload_profile_pict'),
    path('change/password/<nopeg>/', change_pass, name='change_pass'),
    path('webmail', webmail_redirect, name='webmail_redirect')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

titan-misuzhima/ui/urls.py
from django.urls import path
from ui.views import *
from ui.tax import *

urlpatterns = [
    path('', homepage, name="homepage"),
    path('staff/', staff_index, name="staff_index"),
    path('staff/add/', staff_add, name="staff_add"),
    path('staff/edit/<nopeg>/', staff_edit, name="staff_edit"),
    path('staff/detail/<nopeg>/', staff_detail, name="staff_detail"),
    path('staff/upload/', staff_upload, name="staff_upload"),
    path('delete/staff/<nopeg>/', delete_staff, name="delete_staff"),
    path('add/staff/', add_staff_detail, name="add_staff_detail"),
    path('edit/detail/', edit_staff_detail, name="upload_detail"),
    path('upload/detail/', upload_staff_detail, name="upload_detail"),

    path('payroll/', payroll_index, name="payroll_index"),
    path('payroll/add/<bulan>/<tipe>/', payroll_add, name="payroll_add"),
    path('payroll/history/', payroll_history, name="payroll_history"),
    path('payroll/edit/<nopeg>/<bulan>/<tipe>/',
         payroll_edit, name="payroll_edit"),
    path('payroll/view/<filetype>/<nopeg>/<bulan>/<tipe>/',
         payroll_view, name="payroll_view"),
    path('payroll/upload/', payroll_upload, name="payroll_upload"),
    path('publish/payroll/<bulan>/<tipe>/',
         publish_payroll, name="publish_payroll"),
    path('add/payroll/', add_payroll_detail, name="add_payroll_detail"),
    path('edit/payroll/<pk>/', edit_payroll_detail, name="payroll_detail"),
    path('upload/payroll/', upload_payroll_detail, name="upload_payroll"),


    path('recalculate/tax/<bulan>/<tipe>/',
         recalculate_tax, name="recalculate_tax"),

    path('profile/', profile_index, name="profile_index"),
    path('profile/access/', profile_access, name="profile_acess"),
    path('profile/add/', add_staff_access, name="add_staff_access"),

    path('pdf/<nopeg>/<bulan>/<tipe>/', Pdf.as_view()),
    path('pdf/<bulan>/<tipe>/', BulkPdf.as_view()),
    path('pdf/staff/', StaffBulkPdf.as_view()),

    path('excel/<bulan>/<tipe>/', dot_matrix_format, name="dot_matrix"),

    path('export/', export_index, name="export_index"),
    path('export/payroll/<month>/<format>/',
         export_payroll_xlsx, name="export_payroll"),
    path('export/staff/', export_staff_xlsx, name="export_staff"),
    path('export/access/', export_access_xlsx, name="export_access"),

    # new iteration
    path('staff/edit-status/<nopeg>/',
         edit_status_form, name="edit_status_form"),
    path('edit-status/staff/', edit_status_detail, name="edit_status_detail"),
    path('staff/upload/edit', upload_staff_edit, name="upload_staff_edit"),
    path('profile/edit/<pk>', edit_staff_access, name="edit_staff_access"),
    path('edit/profile/<pk>', edit_staff_index, name="edit_staff_index"),
    path('delete/profile/<pk>', delete_staff_access,
         name="delete_staff_access"),
    path('dashboard/staff', dashboard_staff, name="dashboard_staff"),
    path('dashboard/payroll', dashboard_payroll, name="dashboard_payroll"),
    path('load/dashboard/payroll', load_dashboard_payroll,
         name="load_dashboard_payroll"),
    path('load/dashboard/hrd', load_dashboard_hrd, name="load_dashboard_hrd"),
    path('load/dashboard/hrd-current', load_dashboard_hrd_current,
         name="load_dashboard_hrd_current"),
    path('load/chart/payroll', load_chart_payroll, name="load_chart_payroll"),
    path('load/chart/hrd', load_chart_hrd, name="load_chart_hrd"),
    path('load/chart/hrd-current', load_chart_hrd_current,
         name="load_chart_hrd_current"),
    path('load/chart/unit', load_chart_unit, name="load_chart_unit"),


    # run by cron
    path('insert-db-pegawai-per-bulan/', insert_db_pegawai_per_bulan,
         name="insert_db_pegawai_per_bulan"),


    path('tax/', pph_21_formula, name='pph_21')

]

titan-misuzhima/compro/models.py
from django.db import models
from django.core.cache import cache


class SingletonModel(object):
    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        pass

    def set_cache(self):
        cache.set(self.__class__.__name__, self)

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)

        self.set_cache()

    @classmethod
    def load(cls):
        if cache.get(cls.__name__) is None:
            obj, created = cls.objects.get_or_create(pk=1)
            if not created:
                obj.set_cache()
        return cache.get(cls.__name__)


class HeroImage(models.Model):
    BERANDA = 'BERANDA'
    PROFIL = 'PROFIL'
    KEBIJAKAN = 'KEBIJAKAN'
    KARIR = 'KARIR'
    PILIHAN_HALAMAN = (
        (BERANDA, 'Beranda'),
        (PROFIL, 'Profil Petinggi'),
        (KEBIJAKAN, 'Kebijakan Mutu'),
        (KARIR, 'Karir'),
    )
    jenis_halaman = models.CharField(max_length=20, choices=PILIHAN_HALAMAN, default=BERANDA, unique=True,
                                     error_messages={'unique': 'Satu halaman hanya memiliki 1 hero image saja'})
    gambar = models.ImageField()

    class Meta:
        verbose_name_plural = 'Hero Images'


class DeskripsiSingkat(SingletonModel, models.Model):
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Deskripsi Singkat'


class NilaiPerusahaan(models.Model):
    gambar = models.ImageField()
    judul = models.CharField(max_length=50)
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Nilai Perusahaan'


class Testimoni(models.Model):
    foto = models.ImageField()
    nama = models.CharField(max_length=50)
    jabatan = models.CharField(max_length=100)
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Testimoni'


class FotoGaleri(models.Model):
    foto = models.ImageField()
    deskripsi = models.TextField(max_length=500)

    class Meta:
        verbose_name_plural = 'Foto Galeri'


class DeskripsiLengkap(SingletonModel, models.Model):
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Deskripsi Lengkap'


class VisiMisi(models.Model):
    VISI = 'VISI'
    MISI = 'MISI'
    PILIHAN_VISI_MISI = (
        (VISI, 'Visi'),
        (MISI, 'Misi'),
    )
    jenis = models.CharField(max_length=20, choices=PILIHAN_VISI_MISI, default=VISI, unique=True,
                             error_messages={'unique': 'Visi atau Misi hanya bisa satu saja'})
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Visi Misi'


class StrukturOrganisasi(SingletonModel, models.Model):
    gambar = models.ImageField()

    class Meta:
        verbose_name_plural = 'Struktur Organisasi'

class ProfilPetinggi(models.Model):
    foto = models.ImageField()
    nama = models.CharField(max_length=50)
    jabatan = models.CharField(max_length=100)
    deskripsi = models.TextField(null=True)

    class Meta:
        verbose_name_plural = 'Profil Petinggi'


class KebijakanMutu(SingletonModel, models.Model):
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Kebijakan Mutu'


class InfoKarir(SingletonModel, models.Model):
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Info Karir'


class Alamat(SingletonModel, models.Model):
    deskripsi = models.TextField()

    class Meta:
        verbose_name_plural = 'Alamat'


class Kontak(models.Model):
    TELEPON = 'TELP'
    FAX = 'FAX'
    PILIHAN_JENIS_KONTAK = (
        (TELEPON, 'Telepon'),
        (FAX, 'Fax'),
    )
    jenis = models.CharField(max_length=20, choices=PILIHAN_JENIS_KONTAK, default=TELEPON)
    nomor = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = 'Kontak'


class SosialMedia(models.Model):
    FACEBOOK = 'FB'
    TWITTER = 'TWITTER'
    GOOGLE_PLUS = 'GPLUS'
    PILIHAN_SOSIAL_MEDIA = (
        (FACEBOOK, 'Facebook'),
        (TWITTER, 'Twitter'),
        (GOOGLE_PLUS, 'Google Plus'),
    )
    jenis = models.CharField(max_length=20, choices=PILIHAN_SOSIAL_MEDIA, default=FACEBOOK, unique=True,
                             error_messages={'unique': 'Jenis Sosial Media ini sudah terdaftar'})
    url = models.URLField()

    class Meta:
        verbose_name_plural = 'Sosial Media'

titan-misuzhima/compro/views.py
from django.shortcuts import render
from .models import HeroImage, DeskripsiSingkat, DeskripsiLengkap, NilaiPerusahaan, Testimoni, FotoGaleri, VisiMisi, \
    ProfilPetinggi, Alamat, Kontak, SosialMedia, KebijakanMutu, StrukturOrganisasi, InfoKarir


def beranda(request):
    response = init_response(page_title='Beranda')

    if DeskripsiSingkat.objects.all().count() > 0:
        deskripsi_singkat = DeskripsiSingkat.objects.all().last()
        response['deskripsi_singkat'] = deskripsi_singkat

    nilai_perusahaan = NilaiPerusahaan.objects.all()[:4]
    foto_galeri = FotoGaleri.objects.all()
    testimoni = Testimoni.objects.all()
    response['nilai_perusahaan'] = nilai_perusahaan
    response['foto_galeri'] = foto_galeri
    response['testimoni'] = testimoni[testimoni.count() - 3:] if testimoni.count() > 2 else testimoni
    return render(request, 'beranda.html', response)


def profil_petinggi(request):
    response = init_response(page_title='Profil Petinggi')

    if DeskripsiLengkap.objects.all().count() > 0:
        deskripsi_lengkap = DeskripsiLengkap.objects.all().last()
        response['deskripsi_lengkap'] = deskripsi_lengkap
    if VisiMisi.objects.filter(jenis='VISI').exists():
        visi = VisiMisi.objects.get(jenis='VISI')
        response['visi'] = visi
    if VisiMisi.objects.filter(jenis='MISI').exists():
        misi = VisiMisi.objects.get(jenis='MISI')
        response['misi'] = misi
    if StrukturOrganisasi.objects.all().count() > 0:
        struktur_organisasi = StrukturOrganisasi.objects.all().last()
        response['struktur_organisasi'] = struktur_organisasi

    profil_petinggi = ProfilPetinggi.objects.all()[:5]
    response['profil_petinggi'] = profil_petinggi
    return render(request, 'profil-petinggi.html', response)


def kebijakan_mutu(request):
    response = init_response(page_title='Kebijakan Mutu')

    if KebijakanMutu.objects.all().count() > 0:
        kebijakan_mutu = KebijakanMutu.objects.all().last()
        response['kebijakan_mutu'] = kebijakan_mutu

    return render(request, 'kebijakan-mutu.html', response)


def karir(request):
    response = init_response(page_title='Karir')

    if InfoKarir.objects.all().count() > 0:
        info_karir = InfoKarir.objects.all().last()
        response['info_karir'] = info_karir

    return render(request, 'karir.html', response)


def init_response(page_title):
    response = {'title': page_title}

    if HeroImage.objects.filter(jenis_halaman=page_title.split(" ")[0].upper()):
        hero_img = HeroImage.objects.get(jenis_halaman=page_title.split(" ")[0].upper())
        response['hero_img'] = hero_img
    if Alamat.objects.all().count() > 0:
        alamat = Alamat.objects.all().last()
        response['alamat'] = alamat
    if Kontak.objects.filter(jenis='TELP').exists():
        telepon = Kontak.objects.filter(jenis='TELP')
        response['telepon'] = telepon
    if Kontak.objects.filter(jenis='FAX').exists():
        fax = Kontak.objects.filter(jenis='FAX')
        response['fax'] = fax
    if SosialMedia.objects.filter(jenis='FB').exists():
        fb = SosialMedia.objects.get(jenis='FB')
        response['fb'] = fb
    if SosialMedia.objects.filter(jenis='TWITTER').exists():
        twitter = SosialMedia.objects.get(jenis='TWITTER')
        response['twitter'] = twitter
    if SosialMedia.objects.filter(jenis='GPLUS').exists():
        gplus = SosialMedia.objects.get(jenis='GPLUS')
        response['gplus'] = gplus

    return response

titan-misuzhima/compro/templates/partials/footer.html
{% load static %}
{% load staticfiles %}

<footer class="footer page-footer font-small px-5 py-5">
    <div class="container text-center text-md-left">
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-3">
                <div class="row">
                    <div class="footer-brand col-md-2">
                        <img src="{% static 'img/logo_bas.png' %}" width="55" height="45">
                    </div>
                    <div class="col-md-10">
                        <a href="/">
                            <h5 class="footer-title">MIZUSHIMA METAL WORKS INDONESIA</h5>
                        </a>
                        <p>{{ alamat.deskripsi }}</p>
                        <p>Telp. {% for t in telepon %} {{ t.nomor }}, {% endfor %}<br>
                            Fax. {% for f in fax %} {{ f.nomor }} {% endfor %}</p>
                    </div>
                </div>
            </div>
            <hr class="clearfix w-100 d-md-none pb-3">
            <div class="col-md-3 mb-md-0 mb-3">
                <a href="/profil">
                    <h5 class="text-uppercase footer-title">Profil Petinggi</h5>
                </a>
                <ul class="list-unstyled">
                    <li>
                        <a href="#deskripsi">Tentang BAS</a>
                    </li>
                    <li>
                        <a href="#visiMisi">Visi Misi</a>
                    </li>
                    <li>
                        <a href="#profil">Profil Petinggi</a>
                    </li>
                </ul>
                <a href="/kebijakan-mutu">
                    <h5 class="text-uppercase footer-title">Kebijakan Mutu</h5>
                </a>
                <a href="/karir">
                    <h5 class="text-uppercase footer-title">Karir</h5>
                </a>
                <a href="{% url 'mobile' %}">
                    <h5 class="text-uppercase footer-title">Portal Pegawai</h5>
                </a>
            </div>
            <hr class="clearfix w-100 d-md-none pb-3">
            <div class="col-md-3 mb-md-0 mb-3 social-media">
                <div>
                    <h5 class="text-uppercase footer-title">Ikuti kami</h5>
                    <a class="logo-sosmed" target="_blank" rel="noopener noreferrer" href="{{ fb.url }}"><img
                            src="{% static 'img/icon-facebook.png' %}"></a>
                    <a class="logo-sosmed" target="_blank" rel="noopener noreferrer" href="{{ twitter.url }}"><img
                            src="{% static 'img/icon-twitter.png' %}"></i></a>
                    <a class="logo-sosmed" target="_blank" rel="noopener noreferrer" href="{{ gplus.url }}"><img
                            src="{% static 'img/icon-googleplus.png' %}"></a>
                </div>
            </div>
        </div>
    </div>
</footer>

titan-misuzhima/compro/templates/partials/header.html
{% load static %}
{% load staticfiles %}

<nav class="navbar fixed-top navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand" href="/">
        <img src="{% static 'img/logo_bas.png' %}" width="55" height="45" alt="logo-bas">
    </a>
    <button class="navbar-toggler header-button" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <div class="animated-hamburger"><span></span><span></span><span></span></div>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'compro:beranda' %}">BERANDA</span></a>
            <a class="nav-item nav-link" href="{% url 'compro:profil' %}">PROFIL PETINGGI</a>
            <a class="nav-item nav-link" href="{% url 'compro:kebijakan-mutu' %}">KEBIJAKAN MUTU</a>
            <a class="nav-item nav-link" href="{% url 'compro:karir' %}">KARIR</a>
            <a class="nav-item nav-link" href="{% url 'mobile' %}">PORTAL PEGAWAI</a>
        </div>
    </div>
</nav>